name: timer_button
description: Timer Button is a Flutter package that offers a customizable button widget capable of activation after a designated time interval.
version: 2.1.1
homepage: https://github.com/ProjectAJ14/timer_button
documentation: https://github.com/ProjectAJ14/timer_button
repository: https://github.com/ProjectAJ14/timer_button
issue_tracker: https://github.com/ProjectAJ14/timer_button/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
flutter:

screenshots:
  - description: Demo Button.
    path: screenshots/demo.png